### ISSUE TITLE
大佬 你软工操作系统课设剩下的几道题会搞吗？

### ISSUE THREAD

**Issue by WYHHH-MAX** [Quin293/2024-XDU-OS-Course-Design#1]
大佬 你软工操作系统课设剩下的几道题会搞吗？

**Comment by Quin293** [comment]
哈哈不太会，最近在学




大秦帝锅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Quin293/2024-XDU-OS-Course-Design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月23日(星期二) 晚上8:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Quin293/2024-XDU-OS-Course-Design] 大佬 你软工操作系统课设剩下的几道题会搞吗？ (Issue #1)





 
大佬 你软工操作系统课设剩下的几道题会搞吗？

**Comment by WYHHH-MAX** [comment]
哦哦，大佬加油

**Comment by WYHHH-MAX** [comment]
写完后面几道题再更新一下吧，谢谢大佬！！！

**Comment by WYHHH-MAX** [comment]
大佬，Test文件里的0.c 1.c 2.c编译通不过诶

**Comment by Quin293** [comment]
传的文件有问题，等我重新传

**Comment by lajitani-fsy** [comment]
佬，第六题编译test外部的程序出错了，
![bug](https://github.com/Quin293/XDU-OS-Course-Design-2024/assets/116054517/28fc1168-ddce-40ef-a222-85371ebb433e)

**Comment by Quin293** [comment]
> 可能是环境问题呢，你换个路径试试，我用的是openEuler，不行就换这个os，在这个os上按步骤来是没问题的
