### ISSUE TITLE
老大subject7代码

### ISSUE THREAD

**Issue by 9Makabaka** [Quin293/2024-XDU-OS-Course-Design#4]
老大subject7代码终端总显示ERROR: Unknown function: bpf_get_current_task
        exit();
            ~~~~
好像我的内核不支持 bpf_trace_printk()，该怎么改呢拷问了一下午ai了没结果

**Comment by Quin293** [comment]
用的是openeuler吗，openkylin不支持bpftrace

**Comment by 9Makabaka** [comment]
> 用的是openeuler吗，openkylin不支持BPFtrace

用的openEuler

**Comment by Quin293** [comment]
哦哦，我忘记传新的了，那行改成$task = (struct task_struct *)curtask; 就行了

**Comment by 9Makabaka** [comment]
> 哦哦，我忘记传新的了，那行改成$task = （struct task_struct *）curtask;就行了

噢！成功了！谢谢老大
