### ISSUE TITLE
第六题rwbuf.c

### ISSUE THREAD

**Issue by WYHHH-MAX** [Quin293/2024-XDU-OS-Course-Design#5]
#include <linux/uaccess.h>       
#include <linux/cdev.h>
#include <linux/device.h>
大佬，这三行编译报错了怎么办啊？

**Comment by Quin293** [comment]
不清楚呢，我没遇到这个问题，把rwbuf.c和makefile放在同一路径，命令行sudo make 编译，你是这样做的吗

**Comment by WYHHH-MAX** [comment]
写代码的时候就报错了
https://github.com/Quin293/XDU-OS-Course-Design-2024/assets/129677749/513c1449-d800-4994-b0a4-6c1290ee6d49

**Comment by WYHHH-MAX** [comment]
写代码的时候就报错了
https://github.com/Quin293/XDU-OS-Course-Design-2024/assets/129677749/0f2964fe-6eb3-4ea3-982a-908051ab1606

**Comment by WYHHH-MAX** [comment]
没事了大佬 我sb了
