### ISSUE TITLE
subject8老大

### ISSUE THREAD

**Issue by 9Makabaka** [Quin293/2024-XDU-OS-Course-Design#6]
老大用了你的代码编译后重启virtualbox显示failed to daemon for power manager是咋回事，虚拟机整崩溃了吗，得重新安装openeuler吗

**Comment by Quin293** [comment]
不清楚，我基本没怎么遇到过奇奇怪怪的问题，我也不知道如何解决

**Comment by 9Makabaka** [comment]
> 不清楚，我基本没怎么遇到过奇奇怪怪的问题，我也不知道如何解决

老大我运行起来了但是main函数结果显示Syscall Wrong! ret = -1，好像系统调用没安到内核里吗，也没有死机
